name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@772c4490b37ea1c65caf6a53089a38ea1510cf4a # v1.93.0
      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2.7.7
      - name: Install Cloudflare Worker build tools
        run: cargo install -q worker-build
      - name: Build Worker
        run: |
          worker-build --release
      - name: Run (Rust) unit tests
        run: cargo test
      - name: Install Node dependencies
        run: npm install
      - name: Run (Node) integration tests
        run: npm run cucumber
